name: Deploy WordPress app to Azure Web App - My-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./* -x "*.git/*" "*.github/*" "node_modules/*" "*.DS_Store"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: wordpress-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: 'http://my-app-g6gbcdg7hxf5faet.eastus2-01.azurewebsites.net'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: wordpress-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'My-app'
          slot-name: 'production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
